steps:
    - id: "Push da imagem gerada no processo de CI no Container Registry do GCP"
      name: 'gcr.io/cloud-builders/docker'
      args: ['build','-t','gcr.io/$PROJECT_ID/desafiogo:latest','.']

    - id: "Rodando test"
      name: 'gcr.io/cloud-builders/go'
      # env: ["GOPATH=."]
      args: ["test","sum"]

    - id: Run project
      name: "gcr.io/cloud-builders/go"
      # env: ["GOPATH=."]
      args: ["run","sum"]

images:
    - 'gcr.io/$PROJECT_ID/desafiogo:latest'

tags: ['cloud-builders-community']